---
- name: install zsh
  apt:
    name: zsh
    state: present
  become: yes

- name: install oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh
    depth: 1

- name: copy zshrc
  copy:
    src: zsh/zshrc
    dest: ~/.zshrc
    mode: 0644

- name: make zsh the default shell
  shell: chsh -s $(which zsh)

